coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%

    patch:
      default:
        target: 80%

# coverage exclusions
# 
# all exclusions are explicit and listed here. we're not 
# using directives like coverage:ignore-start/end/file.
#

ignore:
  # - see enums_test.dart
  - "packages/rad/lib/src/core/common/enums.dart"
  
  # - see browser_window_test.dart
  - "packages/rad/lib/src/core/interface/window/delegates/browser_window.dart"

  # - tests not added for listview widget yet
  - "packages/rad/lib/src/widgets/list_view.dart"

  # - see workflow reconciler.yml
  - "packages/rad/lib/src/core/renderer/reconciler.dart"
