name: rad
version: 0.8.0-dev
description: >
  A zero-dependency frontend framework for writing web apps in plain Dart. Inspired from Flutter.

homepage: https://github.com/erlage/rad
documentation: https://github.com/erlage/rad#readme

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  web:

dependencies: 
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.1
  build: ^2.3.0
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3

  # style/lint helpers
  
  import_sorter: ^4.6.0


import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - \/test\/*