name: rad_test
version: 0.4.0
description: A testing library for testing applications that are written using Rad.

homepage: https://github.com/erlage/rad
documentation: https://github.com/erlage#readme

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  web:

dependencies:
  rad: ^0.10.0
  meta: ^1.8.0
  test: ^1.21.1

dev_dependencies:
  import_sorter: ^4.6.0

import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - \/test\/*
