name: rad_hooks
version: 0.1.0
publish_to: none
description: A set of commonly used hooks for using in your Rad applications.

homepage: https://github.com/erlage/rad
documentation: https://github.com/erlage/rad#readme
repository: https://github.com/erlage/rad
issue_tracker: https://github.com/erlage/rad/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  web:

dependencies:
  rad: '>=1.2.0 <2.0.0'
    
  meta: ^1.8.0
  test: ^1.21.1

dev_dependencies:
  rad_test: ^0.6.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - \/test\/*

dependency_overrides:
  rad:
    path: ../../packages/rad
