// ignore_for_file: non_constant_identifier_names

// auto-generated. please don't edit this file

import 'package:rad/src/widgets/text.dart';
import 'package:rad/src/widgets/route.dart';
import 'package:rad/src/widgets/stateful_widget.dart';
import 'package:rad/src/widgets/gesture_detector.dart';
import 'package:rad/src/widgets/stateless_widget.dart';
import 'package:rad/src/widgets/navigator.dart';

final GEN_STYLES_MAIN_CSS = ""
    " /** "
    "    * sensible defaults "
    "    */ "
    "  "
    " html, "
    " body { "
    "     width: 100%; "
    "     height: 100%; "
    "     white-space: nowrap; "
    " } "
    "  "
    "  "
    " /** "
    "    * include padding in box size "
    "    */ "
    "  "
    " * { "
    "     box-sizing: border-box; "
    " } "
    "  "
    "  "
    " /** "
    "    * widgets without styles "
    "    */ "
    "  "
    " [data-wtype=\"$Text\"], "
    " [data-wtype=\"$Route\"], "
    " [data-wtype=\"$StatefulWidget\"], "
    " [data-wtype=\"$GestureDetector\"], "
    " [data-wtype=\"$StatelessWidget\"] { "
    "     /*  "
    "      "
    "     It's important to have each element present inside DOM because "
    "     Rad uses DOM as Element tree. Since these widgets shouldn't have "
    "     any impact on styles, we are using display: contents here. "
    "  "
    "     Note: contents is not widely supported by the browsers. If Browser  "
    "     support ever becomes a problem, we can introduce a Element tree to  "
    "     fix this problem.  "
    "     */ "
    "     display: contents; "
    " } "
    "  "
    "  "
    " /** "
    "    * navigator is the only widget that has default styles "
    "    */ "
    "  "
    " [data-wtype=\"$Navigator\"] { "
    "     width: 100%; "
    "     height: 100%; "
    "     display: block; "
    " } "
    "  "
    "  "
    " /** "
    "    * system "
    "    */ "
    "  "
    " .rad-hidden { "
    "     display: none!important; "
    "     visibility: hidden!important; "
    " } ";
