// ignore_for_file: non_constant_identifier_names

// auto-generated. please don't edit this file

import 'package:rad/src/widgets/elements/text.dart';
import 'package:rad/src/widgets/layout/container.dart';
import 'package:rad/src/widgets/layout/stack.dart';
import 'package:rad/src/widgets/layout/align.dart';
import 'package:rad/src/widgets/layout/positioned.dart';
import 'package:rad/src/widgets/layout/overlay/overlay.dart';
import 'package:rad/src/widgets/layout/overlay/overlay_entry.dart';
import 'package:rad/src/widgets/main/stateful_widget.dart';
import 'package:rad/src/widgets/main/stateless_widget.dart';
import 'package:rad/src/widgets/misc/gesture_detector.dart';

final GEN_STYLES_MAIN_CSS = ""
    " html, "
    " body { "
    "     width: 100%; "
    "     height: 100%; "
    "     white-space: nowrap; "
    " } "
    "  "
    "  "
    " /** "
    "    * default text style "
    "    */ "
    "  "
    " [data-wtype=\"$Text\"] { "
    "     width: auto; "
    "     white-space: normal; "
    "     word-wrap: break-word; "
    " } "
    "  "
    "  "
    " /** "
    "    * widgets without scrolls "
    "    * i.e widget's inner content will not be scrollable "
    "    */ "
    "  "
    " [data-wtype=\"$Container\"], "
    " [data-wtype=\"$Stack\"], "
    " [data-wtype=\"$Align\"], "
    " [data-wtype=\"$Positioned\"] { "
    "     overflow: hidden; "
    " } "
    "  "
    "  "
    " /** "
    "    * widgets that should take as much space as possible "
    "    */ "
    "  "
    " [data-wtype=\"$Align\"], "
    " [data-wtype=\"$Stack\"], "
    " [data-wtype=\"$Container\"], "
    " [data-wtype=\"$Overlay\"], "
    " [data-wtype=\"$OverlayEntry\"], "
    "  "
    " /*  "
    "  below widgets are not stylable. only way to "
    "  limit their bounds is to wrap them in a stylable "
    "  widget such as container. "
    " */ "
    "  "
    " [data-wtype=\"$StatefulWidget\"], "
    " [data-wtype=\"$StatelessWidget\"], "
    " [data-wtype=\"$GestureDetector\"], "
    "  "
    " /*  "
    "  target is not a widget it refers to the div where app is mounted "
    " */ "
    "  "
    " [data-wtype=\"Target\"] { "
    "     width: 100%; "
    "     height: 100%; "
    "     display: block; "
    " } "
    "  "
    "  "
    " /** "
    "    * widgets that has relative position "
    "    * this allow child widgets to absolutly position themselves "
    "    */ "
    "  "
    " [data-wtype=\"$Align\"], "
    " [data-wtype=\"$Overlay\"], "
    " [data-wtype=\"$Stack\"] { "
    "     position: relative; "
    " } "
    "  "
    "  "
    " /** "
    "    * widgets with absolute position "
    "    */ "
    "  "
    " [data-wtype=\"$OverlayEntry\"], "
    "  "
    " /* align childs */ "
    "  "
    " [data-wtype=\"$Align\"]>div, "
    " [data-wtype=\"$Align\"]>span, "
    "  "
    " /* stack childs */ "
    "  "
    " [data-wtype=\"$Stack\"]>div, "
    " [data-wtype=\"$Stack\"]>span { "
    "     position: absolute; "
    " } "
    "  "
    "  "
    " /** "
    "    * system "
    "    */ "
    "  "
    " .rad-hidden { "
    "     display: none!important; "
    "     visibility: hidden!important; "
    " } ";
