name: rad_routing_example

version: 0.7.1

homepage: https://github.com/erlage/rad
documentation: https://github.com/erlage/rad#readme

environment:
  sdk: '>=2.16.1 <3.0.0'

platforms:
  web:

dependencies:
  rad:

dev_dependencies:
  build: ^2.2.1
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
  test: ^1.20.2

dependency_overrides:
  rad:
    path: ../