name: rad_routing_example

version: 0.7.1

homepage: https://github.com/erlage/rad
documentation: https://github.com/erlage/rad#readme

environment:
  sdk: '>=2.16.1 <3.0.0'

platforms:
  web:

dependencies:
  rad:

dev_dependencies:
  test: ^1.21.1
  build: ^2.3.0
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3

dependency_overrides:
  rad:
    path: ../../