/// HTML widgets.
///
library widgets_html;

export 'src/widgets/html/headings.dart';
export 'src/widgets/html/abbreviation.dart' show Abbreviation;
export 'src/widgets/html/article.dart' show Article;
export 'src/widgets/html/code.dart' show Code;
export 'src/widgets/html/header.dart' show Header;
export 'src/widgets/html/footer.dart' show Footer;
export 'src/widgets/html/navigation.dart' show Navigation;
export 'src/widgets/html/span.dart' show Span;
export 'src/widgets/html/small.dart' show Small;
export 'src/widgets/html/strike_through.dart' show StrikeThrough;
export 'src/widgets/html/strong.dart' show Strong;
export 'src/widgets/html/idiomatic.dart' show Idiomatic;
export 'src/widgets/html/sub_script.dart' show SubScript;
export 'src/widgets/html/super_script.dart' show SuperScript;
export 'src/widgets/html/division.dart' show Division;
export 'src/widgets/html/anchor.dart' show Anchor;
export 'src/widgets/html/blockquote.dart' show Blockquote;
export 'src/widgets/html/horizontal_rule.dart' show HorizontalRule;
export 'src/widgets/html/label.dart' show Label;
export 'src/widgets/html/legend.dart' show Legend;
export 'src/widgets/html/iframe.dart' show IFrame;
export 'src/widgets/html/break_line.dart' show BreakLine;
export 'src/widgets/html/image.dart' show Image;
export 'src/widgets/html/canvas.dart' show Canvas;
export 'src/widgets/html/paragraph.dart' show Paragraph;
export 'src/widgets/html/unordered_list.dart' show UnOrderedList;
export 'src/widgets/html/list_item.dart' show ListItem;
export 'src/widgets/html/button.dart' show Button;
export 'src/widgets/html/select.dart' show Select;
export 'src/widgets/html/option.dart' show Option;
export 'src/widgets/html/progress.dart' show Progress;
export 'src/widgets/html/textarea.dart' show TextArea;
export 'src/widgets/html/form.dart' show Form;
export 'src/widgets/html/fieldset.dart' show FieldSet;
export 'src/widgets/html/input_text.dart' show InputText;
export 'src/widgets/html/input_checkbox.dart' show InputCheckBox;
export 'src/widgets/html/input_radio.dart' show InputRadio;
export 'src/widgets/html/input_file.dart' show InputFile;
export 'src/widgets/html/input_submit.dart' show InputSubmit;
export 'src/widgets/html/table.dart' show Table;
export 'src/widgets/html/caption.dart' show Caption;
export 'src/widgets/html/table_column.dart' show TableColumn;
export 'src/widgets/html/table_column_group.dart' show TableColumnGroup;
export 'src/widgets/html/table_head.dart' show TableHead;
export 'src/widgets/html/table_body.dart' show TableBody;
export 'src/widgets/html/table_data_cell.dart' show TableDataCell;
export 'src/widgets/html/table_header_cell.dart' show TableHeaderCell;
export 'src/widgets/html/table_foot.dart' show TableFoot;
export 'src/widgets/html/table_row.dart' show TableRow;
