// ignore_for_file: constant_identifier_names

// auto-generated. please don't edit this file

const GEN_STYLES_MAIN_CSS = ""
    " html, "
    " body { "
    "     width: 100%; "
    "     height: 100%; "
    " } "
    "  "
    "  "
    " /** "
    "    * reset styles for wigets that otherwise might inherit defaults "
    "    * from their corresponding HTML tag in-use "
    "    */ "
    "  "
    " [data-wtype=\"StatefulWidget\"], "
    " [data-wtype=\"StatelessWidget\"], "
    " [data-wtype=\"GestureDetector\"], "
    " [data-wtype=\"Container\"], "
    " [data-wtype=\"Text\"] { "
    "     all: unset; "
    "     overflow: hidden; "
    " } "
    "  "
    "  "
    " /** "
    "    * widgets that should take as much space as possible "
    "    */ "
    "  "
    " [data-wtype=\"Target\"] { "
    "     width: 100%; "
    "     height: 100%; "
    "     display: block; "
    " } ";
