// ignore_for_file: directives_ordering
// ignore_for_file: camel_case_types

/// Visual-JSX ready HTML widgets
///
library rad_html_vscode;

import 'package:rad_html_vscode/src/html/abbreviation.dart';
import 'package:rad_html_vscode/src/html/address.dart';
import 'package:rad_html_vscode/src/html/anchor.dart';
import 'package:rad_html_vscode/src/html/article.dart';
import 'package:rad_html_vscode/src/html/aside.dart';
import 'package:rad_html_vscode/src/html/audio.dart';
import 'package:rad_html_vscode/src/html/bidirectional_isolate.dart';
import 'package:rad_html_vscode/src/html/bidirectional_text_override.dart';
import 'package:rad_html_vscode/src/html/block_quote.dart';
import 'package:rad_html_vscode/src/html/button.dart';
import 'package:rad_html_vscode/src/html/canvas.dart';
import 'package:rad_html_vscode/src/html/citation.dart';
import 'package:rad_html_vscode/src/html/data.dart';
import 'package:rad_html_vscode/src/html/data_list.dart';
import 'package:rad_html_vscode/src/html/definition.dart';
import 'package:rad_html_vscode/src/html/deleted_text.dart';
import 'package:rad_html_vscode/src/html/description_details.dart';
import 'package:rad_html_vscode/src/html/description_list.dart';
import 'package:rad_html_vscode/src/html/description_term.dart';
import 'package:rad_html_vscode/src/html/details.dart';
import 'package:rad_html_vscode/src/html/dialog.dart';
import 'package:rad_html_vscode/src/html/division.dart';
import 'package:rad_html_vscode/src/html/embed_external.dart';
import 'package:rad_html_vscode/src/html/embed_text_track.dart';
import 'package:rad_html_vscode/src/html/emphasis.dart';
import 'package:rad_html_vscode/src/html/fieldset.dart';
import 'package:rad_html_vscode/src/html/figure.dart';
import 'package:rad_html_vscode/src/html/figure_caption.dart';
import 'package:rad_html_vscode/src/html/footer.dart';
import 'package:rad_html_vscode/src/html/form.dart';
import 'package:rad_html_vscode/src/html/header.dart';
import 'package:rad_html_vscode/src/html/headings.dart';
import 'package:rad_html_vscode/src/html/horizontal_rule.dart';
import 'package:rad_html_vscode/src/html/idiomatic.dart';
import 'package:rad_html_vscode/src/html/iframe.dart';
import 'package:rad_html_vscode/src/html/image.dart';
import 'package:rad_html_vscode/src/html/image_map.dart';
import 'package:rad_html_vscode/src/html/image_map_area.dart';
import 'package:rad_html_vscode/src/html/inline_code.dart';
import 'package:rad_html_vscode/src/html/inline_quotation.dart';
import 'package:rad_html_vscode/src/html/input.dart';
import 'package:rad_html_vscode/src/html/inserted_text.dart';
import 'package:rad_html_vscode/src/html/keyboard_input.dart';
import 'package:rad_html_vscode/src/html/label.dart';
import 'package:rad_html_vscode/src/html/legend.dart';
import 'package:rad_html_vscode/src/html/line_break.dart';
import 'package:rad_html_vscode/src/html/line_break_opportunity.dart';
import 'package:rad_html_vscode/src/html/list_item.dart';
import 'package:rad_html_vscode/src/html/mark_text.dart';
import 'package:rad_html_vscode/src/html/media_source.dart';
import 'package:rad_html_vscode/src/html/menu.dart';
import 'package:rad_html_vscode/src/html/meter.dart';
import 'package:rad_html_vscode/src/html/navigation.dart';
import 'package:rad_html_vscode/src/html/option.dart';
import 'package:rad_html_vscode/src/html/option_group.dart';
import 'package:rad_html_vscode/src/html/ordered_list.dart';
import 'package:rad_html_vscode/src/html/output.dart';
import 'package:rad_html_vscode/src/html/paragraph.dart';
import 'package:rad_html_vscode/src/html/picture.dart';
import 'package:rad_html_vscode/src/html/portal.dart';
import 'package:rad_html_vscode/src/html/preformatted_text.dart';
import 'package:rad_html_vscode/src/html/progress.dart';
import 'package:rad_html_vscode/src/html/ruby_annotation.dart';
import 'package:rad_html_vscode/src/html/ruby_fallback_parenthesis.dart';
import 'package:rad_html_vscode/src/html/ruby_text.dart';
import 'package:rad_html_vscode/src/html/sample_output.dart';
import 'package:rad_html_vscode/src/html/select.dart';
import 'package:rad_html_vscode/src/html/small.dart';
import 'package:rad_html_vscode/src/html/span.dart';
import 'package:rad_html_vscode/src/html/strike_through.dart';
import 'package:rad_html_vscode/src/html/strong.dart';
import 'package:rad_html_vscode/src/html/sub_script.dart';
import 'package:rad_html_vscode/src/html/summary.dart';
import 'package:rad_html_vscode/src/html/super_script.dart';
import 'package:rad_html_vscode/src/html/table.dart';
import 'package:rad_html_vscode/src/html/table_body.dart';
import 'package:rad_html_vscode/src/html/table_caption.dart';
import 'package:rad_html_vscode/src/html/table_column.dart';
import 'package:rad_html_vscode/src/html/table_column_group.dart';
import 'package:rad_html_vscode/src/html/table_data_cell.dart';
import 'package:rad_html_vscode/src/html/table_foot.dart';
import 'package:rad_html_vscode/src/html/table_head.dart';
import 'package:rad_html_vscode/src/html/table_header_cell.dart';
import 'package:rad_html_vscode/src/html/table_row.dart';
import 'package:rad_html_vscode/src/html/textarea.dart';
import 'package:rad_html_vscode/src/html/time.dart';
import 'package:rad_html_vscode/src/html/unordered_list.dart';
import 'package:rad_html_vscode/src/html/variable.dart';
import 'package:rad_html_vscode/src/html/video.dart';

typedef a = Anchor;
typedef abbr = Abbreviation;
typedef address = Address;
typedef area = ImageMapArea;
typedef article = Article;
typedef aside = Aside;
typedef audio = Audio;
typedef bdi = BidirectionalIsolate;
typedef bdo = BidirectionalTextOverride;
typedef blockquote = BlockQuote;
typedef br = LineBreak;
typedef button = Button;
typedef canvas = Canvas;
typedef caption = TableCaption;
typedef cite = Citation;
typedef code = InlineCode;
typedef col = TableColumn;
typedef colgroup = TableColumnGroup;
typedef data = Data;
typedef datalist = DataList;
typedef dd = DescriptionDetails;
typedef del = DeletedText;
typedef details = Details;
typedef dfn = Definition;
typedef dialog = Dialog;
typedef div = Division;
typedef dl = DescriptionList;
typedef dt = DescriptionTerm;
typedef em = Emphasis;
typedef embed = EmbedExternal;
typedef fieldset = FieldSet;
typedef figcaption = FigureCaption;
typedef figure = Figure;
typedef footer = Footer;
typedef form = Form;
typedef h1 = Heading1;
typedef h2 = Heading2;
typedef h3 = Heading3;
typedef h4 = Heading4;
typedef h5 = Heading5;
typedef h6 = Heading6;
typedef header = Header;
typedef hr = HorizontalRule;
typedef i = Idiomatic;
typedef iframe = IFrame;
typedef img = Image;
typedef input = Input;
typedef ins = InsertedText;
typedef kbd = KeyboardInput;
typedef label = Label;
typedef legend = Legend;
typedef li = ListItem;
typedef map = ImageMap;
typedef mark = MarkText;
typedef menu = Menu;
typedef meter = Meter;
typedef nav = Navigation;
typedef ol = OrderedList;
typedef optgroup = OptionGroup;
typedef option = Option;
typedef output = Output;
typedef p = Paragraph;
typedef picture = Picture;
typedef portal = Portal;
typedef pre = PreformattedText;
typedef progress = Progress;
typedef q = InlineQuotation;
typedef rp = RubyFallbackParenthesis;
typedef rt = RubyText;
typedef ruby = RubyAnnotation;
typedef s = StrikeThrough;
typedef samp = SampleOutput;
typedef select = Select;
typedef small = Small;
typedef source = MediaSource;
typedef span = Span;
typedef strong = Strong;
typedef sub = SubScript;
typedef summary = Summary;
typedef sup = SuperScript;
typedef table = Table;
typedef tbody = TableBody;
typedef td = TableDataCell;
typedef textarea = TextArea;
typedef tfoot = TableFoot;
typedef th = TableHeaderCell;
typedef thead = TableHead;
typedef time = Time;
typedef tr = TableRow;
typedef track = EmbedTextTrack;
typedef ul = UnOrderedList;
typedef vartag = Variable;
typedef video = Video;
typedef wbr = LineBreakOpportunity;
