name: 'Package generator: Custom HTML widgets'

on:
  workflow_dispatch:

  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Run build
        run: |
          cd tool/pkg-gen-html-widgets
          bash test_build.sh
