name: Rad(test-pkg)

on:
  workflow_dispatch:

  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]
  
jobs:
  analyze: 
    runs-on: ubuntu-latest
    name: Analyze
    strategy:
      matrix:
        dart-sdk-version: [3.2.0]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-sdk-version }}

      - name: Run analyze
        run: |
          cd packages/rad_test
          dart pub get
          dart format --output=none --set-exit-if-changed .
          dart analyze --fatal-infos

  tests:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        dart-sdk-version: [2.17.0, 3.0.0]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-sdk-version }}
      
      - name: Run tests
        run: |
          cd packages/rad_test
          dart pub get
          dart pub run test --coverage="coverage"
          dart pub global activate coverage
          $HOME/.pub-cache/bin/format_coverage --lcov --in=coverage --out=rad_test.lcov --report-on=lib
          mv rad_test.lcov ../../rad_test.dart.${{ matrix.dart-sdk-version }}.lcov

      - name: Publish to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: rad_test.dart.${{ matrix.dart-sdk-version }}.lcov
          verbose: true
