name: Reconciler

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - 'packages/rad/pubspec.yaml'
      - 'packages/rad/lib/src/core/renderer/reconciler.dart'
  
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/rad/lib/src/core/renderer/reconciler.dart'
  
jobs:
  tests_w_wo_optimizations:
    runs-on: ubuntu-latest
    name: Run tests both w/ & w/o optimizations

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.0
      
      - name: Run tests
        run: |
          cd packages/rad
          dart pub get
          cd tool
          dart run setup_reconciler_test.dart
          cd ..
          sh reconciler_tests.sh
