name: Check spelling

on:
  workflow_dispatch:

  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

jobs:
  cSpell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v1
        with:
          root: '../../'
          config: '../../cspell.json'
          strict: true
          incremental_files_only: true
