name: Check spelling

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cSpell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v1
        with:
          config: './cspell.json'
          files: "**"
          strict: true
          incremental_files_only: false
